<% project_name = 'adviceappmaggicorp' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= adviceappmaggicorp %>_development

test:
  <<: *default
  database: <%= adviceappmaggicorp %>_test
