require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TakeAdvicesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TakeAdvice. As you add validations to TakeAdvice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TakeAdvicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all take_advices as @take_advices" do
      take_advice = TakeAdvice.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:take_advices)).to eq([take_advice])
    end
  end

  describe "GET #show" do
    it "assigns the requested take_advice as @take_advice" do
      take_advice = TakeAdvice.create! valid_attributes
      get :show, params: {id: take_advice.to_param}, session: valid_session
      expect(assigns(:take_advice)).to eq(take_advice)
    end
  end

  describe "GET #new" do
    it "assigns a new take_advice as @take_advice" do
      get :new, params: {}, session: valid_session
      expect(assigns(:take_advice)).to be_a_new(TakeAdvice)
    end
  end

  describe "GET #edit" do
    it "assigns the requested take_advice as @take_advice" do
      take_advice = TakeAdvice.create! valid_attributes
      get :edit, params: {id: take_advice.to_param}, session: valid_session
      expect(assigns(:take_advice)).to eq(take_advice)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TakeAdvice" do
        expect {
          post :create, params: {take_advice: valid_attributes}, session: valid_session
        }.to change(TakeAdvice, :count).by(1)
      end

      it "assigns a newly created take_advice as @take_advice" do
        post :create, params: {take_advice: valid_attributes}, session: valid_session
        expect(assigns(:take_advice)).to be_a(TakeAdvice)
        expect(assigns(:take_advice)).to be_persisted
      end

      it "redirects to the created take_advice" do
        post :create, params: {take_advice: valid_attributes}, session: valid_session
        expect(response).to redirect_to(TakeAdvice.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved take_advice as @take_advice" do
        post :create, params: {take_advice: invalid_attributes}, session: valid_session
        expect(assigns(:take_advice)).to be_a_new(TakeAdvice)
      end

      it "re-renders the 'new' template" do
        post :create, params: {take_advice: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested take_advice" do
        take_advice = TakeAdvice.create! valid_attributes
        put :update, params: {id: take_advice.to_param, take_advice: new_attributes}, session: valid_session
        take_advice.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested take_advice as @take_advice" do
        take_advice = TakeAdvice.create! valid_attributes
        put :update, params: {id: take_advice.to_param, take_advice: valid_attributes}, session: valid_session
        expect(assigns(:take_advice)).to eq(take_advice)
      end

      it "redirects to the take_advice" do
        take_advice = TakeAdvice.create! valid_attributes
        put :update, params: {id: take_advice.to_param, take_advice: valid_attributes}, session: valid_session
        expect(response).to redirect_to(take_advice)
      end
    end

    context "with invalid params" do
      it "assigns the take_advice as @take_advice" do
        take_advice = TakeAdvice.create! valid_attributes
        put :update, params: {id: take_advice.to_param, take_advice: invalid_attributes}, session: valid_session
        expect(assigns(:take_advice)).to eq(take_advice)
      end

      it "re-renders the 'edit' template" do
        take_advice = TakeAdvice.create! valid_attributes
        put :update, params: {id: take_advice.to_param, take_advice: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested take_advice" do
      take_advice = TakeAdvice.create! valid_attributes
      expect {
        delete :destroy, params: {id: take_advice.to_param}, session: valid_session
      }.to change(TakeAdvice, :count).by(-1)
    end

    it "redirects to the take_advices list" do
      take_advice = TakeAdvice.create! valid_attributes
      delete :destroy, params: {id: take_advice.to_param}, session: valid_session
      expect(response).to redirect_to(take_advices_url)
    end
  end

end
